### ISSUE TITLE
Showing enemy health percentage and numbers

### ISSUE THREAD

**Issue by rtroberts** [kaytotes/ImprovedBlizzardUI_Classic#1]
The addon currently doesn't show any target health and mana information whatsoever. Due to [this API change](https://us.forums.blizzard.com/en/wow/t/wow-classic-ui-api-change-for-unithealth/446596), both the player and target frames could now follow the default UI's configuration setting for target health/mana information (Interface Options -> Display -> Status Text). 

I seem to remember the Retail version of the addon following this behavior, and the player frame currently follows this behavior, so I assume that the feature was removed for classic because the API originally didn't return mob health values. Is that the case?

**Comment by kaytotes** [comment]
Wow, how interesting. Really didn't expect Blizzard to do something like this. #nochanges

Just kidding with that I can see why Blizzard changed it since everyone just runs RealMobHealth anyway so it's a waste of blizzards processing time and clients.

You are correct the Retail version does have this and it was intentionally removed in this due to Classic simply not returning the info. 

Due to that API change I will look at re-implementing this.

**Comment by rtroberts** [comment]
I had time to dig into this a little myself this weekend. 

While Blizzard is now allowing UnitHealth and UnitHealthMax calls, the Classic target frame still doesn't surface `TargetFrameTextureFrameHealthBarText` and `TargetFrameTextureFrameManaBarText` frames. It looks like the retail version of this addon is hooking into those already-existant frames to modify fonts. So simply dropping in retail code won't work, and this target frame text will have to be reimplemented?


I'm very new to WoW addon development, though, so I could be missing something obvious.

**Comment by kaytotes** [comment]
@rtroberts This will be coming in an upcoming release. Basically had to rebuild the original text frames and hook up relevant events.
